name: Setup
description: Setup Nix with Caching

runs:
  using: composite

  steps:
    - name: Create Mount
      shell: bash
      run: sudo mkdir /nix

    - name: Free Space
      uses: easimon/maximize-build-space@v10
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        build-mount-path: /nix
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-docker-images: true
        remove-codeql: true
        overprovision-lvm: true

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_conf: |
          accept-flake-config = true
          build-users-group =

    - name: Setup Cache
      uses: nix-community/cache-nix-action@v6
      if: ${{ ! fromJSON(env.ACT) }}
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1G
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-primary-key: never
