name: Setup
description: Setup Nix & SSH

runs:
  using: composite

  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_conf: |
          accept-flake-config = true
          build-users-group =

    - name: Setup Cache
      uses: nix-community/cache-nix-action@v6
      if: ${{ ! fromJSON(env.ACT) }}
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-primary-key: always
