apiVersion: 1
groups:
  - orgId: 1
    name: Alerts
    folder: Alerts
    interval: 10s
    rules:
      - uid: bej2ujx2gsnwgd
        title: Update
        condition: A
        data:
          - refId: A
            queryType: range
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: "1"
            model:
              editorMode: builder
              expr: count_over_time({unit="comin.service"} |= `finished switching to system configuration` [$__auto])
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              queryType: range
              refId: A
          - refId: B
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        annotations:
          description: "{{ $labels.host }} successfully pulled an update."
          summary: Update Pulled
        labels: {}
        isPaused: false
        notification_settings:
          receiver: ntfy
