name: Deploy

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: x86_64-linux

    outputs:
      nodes: ${{ steps.nodes.outputs.nodes }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Nodes
        id: nodes
        run: echo "nodes=$(nix eval --json --apply builtins.attrNames .#deploy.nodes || echo '[]')" >> "$GITHUB_OUTPUT"

      - name: Checks...
        uses: int128/wait-for-workflows-action@v1.36.0
        with:
          filter-workflow-names: Check

  deploy:
    runs-on: x86_64-linux
    environment: ${{ matrix.node }}

    needs: setup
    strategy:
      matrix:
        node: ${{ fromJSON(needs.setup.outputs.nodes) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Host
        run: ssh-keyscan ${{ matrix.node }} >> known_hosts

      - name: Build & Deploy
        env:
          SSHOPTS: -o UserKnownHostsFile=known_hosts -i /run/agenix/root
        run: nix develop .#deploy --command deploy --skip-checks --remote-build --ssh-opts "$SSHOPTS" .#${{ matrix.node }}

  diff:
    runs-on: ubuntu-latest

    needs: [setup, deploy]
    strategy:
      matrix:
        node: ${{ fromJSON(needs.setup.outputs.nodes) }}

    steps:
      - name: Install NixOS
        uses: nixbuild/nix-quick-install-action@v30

      - name: Install Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:deploy

      - name: Diff OS
        id: diff
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ matrix.node }}
          username: root
          password: root # https://github.com/appleboy/ssh-action/issues/344
          script: |
            old=$(ls -1 /nix/var/nix/profiles/system-*-link | sort -V | tail -n 2 | head -n 1 | sed 's/:$//')
            new=$(ls -1 /nix/var/nix/profiles/system-*-link | sort -V | tail -n 1 | sed 's/:$//')
            nix shell nixpkgs#nvd -c nvd diff $old $new
          capture_stdout: true

      - name: Create Summary
        run: |
          {
            echo "### Host: ${{ matrix.node }}"
            echo "\`\`\`"
            echo "${{ steps.diff.outputs.stdout }}"
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"
