name: Diff

on:
  pull_request:
    types:
      - closed

permissions:
  actions: write

env:
  ACT: false

jobs:
  matrices:
    name: Create Matrices
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    outputs:
      attrs: ${{ steps.get.outputs.attrs }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Get Attributes
        id: get
        run: echo "attrs=$(nix eval --json --apply builtins.attrNames .#toplevel)" >> "$GITHUB_OUTPUT"

  diff:
    name: Diff Attributes
    runs-on: ubuntu-latest

    needs: matrices
    strategy:
      matrix:
        attr: ${{ fromJson(needs.matrices.outputs.attrs) }}

    outputs:
      diff: ${{ steps.build.outputs.diff }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Attribute
        id: build
        env:
          flake_base: github:${{ github.repository }}/${{ github.event.pull_request.base.ref }}
          flake_head: github:${{ github.repository }}/${{ github.event.pull_request.head.ref }}
        run: |
          echo "old=$(nix build --print-out-paths --no-link "$flake_base#toplevel.${{ matrix.attr }}")" >> "$GITHUB_OUTPUT"
          echo "new=$(nix build --print-out-paths --no-link "$flake_head#toplevel.${{ matrix.attr }}")" >> "$GITHUB_OUTPUT"

      - name: Create Diff
        env:
          old: ${{ steps.build.outputs.old }}
          new: ${{ steps.build.outputs.new }}
        run: |
          {
            echo "diff<<EOF"
            nix run nixpkgs#nvd -- diff "$old" "$new"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  release:
    name: Create Release
    runs-on: ubuntu-latest

    needs: diff

    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: diff

      - name: Create Change Log
        id: changelog
        run: |
          changes=""
          for key in $(echo "${{ steps.read.outputs.result }}" | jq -r 'keys[]'); do
            diff=$(echo "${{ steps.read.outputs.result }}" | jq -r ".[$key]")
            changes="${changes}## Diff for $key\n\`\`\`diff\n${diff}\n\`\`\`\n\n"
          done
          {
            echo "changes<<EOF"
            echo "$changes"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: avakar/tag-and-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.merged_at }}
          body: ${{ steps.changelog.outputs.changes }}
