name: Diff

on:
  pull_request:

permissions:
  actions: write

env:
  ACT: false
  BASE: ${{ github.base_ref }}
  HEAD: ${{ github.head_ref }}

jobs:
  matrices:
    name: Create Matrices
    runs-on: ubuntu-latest

    outputs:
      nixos: ${{ steps.nixos.outputs.nixos }}
      home: ${{ steps.home.outputs.home }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Get Systems
        id: nixos
        run: echo "nixos=$(nix eval --json --apply builtins.attrNames .#nixosConfigurations)" >> "$GITHUB_OUTPUT"

      - name: Get Homes
        id: home
        run: echo "home=$(nix eval --json --apply builtins.attrNames .#homeConfigurations)" >> "$GITHUB_OUTPUT"

  nixos:
    name: Diff Systems
    runs-on: ubuntu-latest

    needs: matrices
    strategy:
      matrix:
        system: ${{ fromJson(needs.matrices.outputs.nixos) }}
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Systems
        run: |
          nix build -o old "github:${{ github.repository }}/$BASE#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel"
          nix build -o new "github:${{ github.repository }}/$HEAD#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel"

      - name: Create Diff
        run: |
          {
            echo "\`\`\`"
            nix run nixpkgs#nvd -- diff old new
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"

  home:
    name: Diff Homes
    runs-on: ubuntu-latest

    needs: matrices
    strategy:
      matrix:
        home: ${{ fromJson(needs.matrices.outputs.home) }}
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Homes
        run: |
          nix build -o old "github:${{ github.repository }}/$BASE#homeConfigurations.${{ matrix.home }}.activationPackage"
          nix build -o new "github:${{ github.repository }}/$HEAD#homeConfigurations.${{ matrix.home }}.activationPackage"

      - name: Create Summary
        run: |
          {
            echo "\`\`\`"
            nix run nixpkgs#nvd -- diff old new
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"
