name: Diff

on:
  pull_request:

permissions:
  actions: write

env:
  ACT: false

jobs:
  matrices:
    name: Create Matrices
    runs-on: ubuntu-latest

    outputs:
      nixos: ${{ steps.nixos.outputs.nixos }}
      home: ${{ steps.home.outputs.home }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Get Systems
        id: nixos
        run: echo "nixos=$(nix eval --json --apply builtins.attrNames .#nixosConfigurations)" >> "$GITHUB_OUTPUT"

      - name: Get Homes
        id: home
        run: echo "home=$(nix eval --json --apply builtins.attrNames .#homeConfigurations)" >> "$GITHUB_OUTPUT"

  nixos:
    name: Diff Systems
    runs-on: ubuntu-latest

    needs: matrices
    strategy:
      matrix:
        system: ${{ fromJson(needs.matrices.outputs.nixos) }}
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Install Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:runner

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          until ssh-keyscan runner >> ~/.ssh/known_hosts; do sleep 5; done

      - name: Build Systems
        run: |
          ssh root@runner "
            nix build -o old github:${{ github.repository }}/${{ github.event.pull_request.base.ref }}#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel &> /dev/null
            nix build -o new github:${{ github.repository }}/${{ github.event.pull_request.head.ref }}#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel &> /dev/null
            nix run nixpkgs#nvd -- diff old new
          " > build.diff

      - name: Create Diff
        run: |
          {
            echo "\`\`\`"
            echo build.diff
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"

  home:
    name: Diff Homes
    runs-on: ubuntu-latest

    needs: matrices
    strategy:
      matrix:
        home: ${{ fromJson(needs.matrices.outputs.home) }}
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Install Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:runner

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          until ssh-keyscan runner >> ~/.ssh/known_hosts; do sleep 5; done

      - name: Build Homes
        run: |
          ssh root@runner "
            nix build -o old "github:${{ github.repository }}/${{ github.event.pull_request.base.ref }}#homeConfigurations.${{ matrix.home }}.activationPackage &> /dev/null
            nix build -o new "github:${{ github.repository }}/${{ github.event.pull_request.head.ref }}#homeConfigurations.${{ matrix.home }}.activationPackage &> /dev/null
            nix run nixpkgs#nvd -- diff old new
          " > build.diff

      - name: Create Summary
        run: |
          {
            echo "\`\`\`"
            echo build.diff
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"
