name: Diff

on:
  pull_request:
    types: [closed]

permissions:
  actions: write
  contents: write

env:
  ACT: false

jobs:
  matrices:
    name: Generate Matrices
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    outputs:
      attrs: ${{ steps.get.outputs.attrs }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Get Attributes
        id: get
        run: echo "attrs=$(nix eval --json --apply builtins.attrNames .#toplevel)" >> "$GITHUB_OUTPUT"

  diff:
    name: Diff Attributes
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    needs: matrices
    strategy:
      matrix:
        attr: ${{ fromJson(needs.matrices.outputs.attrs) }}

    outputs:
      diff: ${{ steps.build.outputs.diff }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Attribute
        id: build
        env:
          flake_base: github:${{ github.repository }}/${{ github.event.pull_request.base.ref }}
          flake_head: github:${{ github.repository }}/${{ github.event.pull_request.head.ref }}
        run: |
          echo "old=$(nix build --print-out-paths --no-link "$flake_base#toplevel.${{ matrix.attr }}")" >> "$GITHUB_OUTPUT"
          echo "new=$(nix build --print-out-paths --no-link "$flake_head#toplevel.${{ matrix.attr }}")" >> "$GITHUB_OUTPUT"

      - name: Create Diff
        id: diff
        env:
          old: ${{ steps.build.outputs.old }}
          new: ${{ steps.build.outputs.new }}
        run: |
          {
            echo "diff<<EOF"
            nix run nixpkgs#nvd -- diff "$old" "$new"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Write Output
        uses: cloudposse/github-action-matrix-outputs-write@v1
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.attr }}
          outputs: |-
            diff: ${{ toJson(steps.diff.outputs.diff) }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    needs: diff

    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: diff

      - name: Create Change Log
        run: |
          for attr in $(echo "${{ fromJson(steps.read.outputs.result).diffs }}" | jq -r 'keys[]'); do
            {
              echo "## Diff for $attr"
              echo "\`\`\`"
              echo "${{ fromJson(steps.read.outputs.result).diffs  }}" | jq -r ".[$attr]"
              echo "\`\`\`"
            } >> body.md
          done

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          commit: ${{ github.event.pull_request.head.ref }}
          tag: ${{ github.event.pull_request.head.ref }}
          name: ${{ github.event.pull_request.merged_at }}
          bodyFile: body.md

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest

    needs: release

    steps:
      - name: Delete Branch
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${context.payload.pull_request.head.ref}`,
            })
