name: Diff

on:
  pull_request:

permissions:
  actions: write

env:
  ACT: false

jobs:
  matrices:
    name: Create Matrices
    runs-on: ubuntu-latest

    outputs:
      attrs: ${{ steps.get.outputs.attrs }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Get Systems
        id: get
        run: echo "attrs=$(nix eval --json --apply builtins.attrNames .#toplevel)" >> "$GITHUB_OUTPUT"

  diff:
    name: Diff Attributes
    runs-on: ubuntu-latest

    needs: matrices
    strategy:
      matrix:
        attr: ${{ fromJson(needs.matrices.outputs.attrs) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Attribute
        id: build
        env:
          flake_base: github:${{ github.repository }}/${{ github.event.pull_request.base.ref }}
          flake_head: github:${{ github.repository }}/${{ github.event.pull_request.head.ref }}
        run: |
          echo "old=$(nix build --print-out-paths --no-link "$flake_base#toplevel.${{ matrix.attr }}")" >> "$GITHUB_OUTPUT"
          echo "new=$(nix build --print-out-paths --no-link "$flake_head#toplevel.${{ matrix.attr }}")" >> "$GITHUB_OUTPUT"

      - name: Create Diff
        env:
          old: ${{ steps.build.outputs.old }}
          new: ${{ steps.build.outputs.new }}
        run: |
          {
            echo "\`\`\`"
            nix run nixpkgs#nvd -- diff "$old" "$new"
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"
