name: Docs

on:
  push:
    branches: [main]
  pull_request:

env:
  ACT: false

jobs:
  docstring:
    name: Update Documentation
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - extras=s3-cache
    if: github.event_name == 'push'

    steps:
      - name: Generate Documentation
        uses: Penify-dev/penifydocwf@v1.0.0
        with:
          client_id: ${{ secrets.SNORKELL_CLIENT_ID }}
          api_key: ${{ secrets.SNORKELL_API_KEY }}
          branch_name: "main"

  readme:
    name: Update README
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - extras=s3-cache

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Render Template
        env:
          TEMPLATE: .github/templates/README.template.j2
          OUTPUT: README.md
        run: .github/templates/render.py -t "$TEMPLATE" -o "$OUTPUT"

      - name: Format Repository
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
