name: Format

on:
  push:
    branches: [main]
  pull_request:

env:
  ACT: 0

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          use-cache: ${{ !env.ACT }}

      - name: Format Repo
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
