name: Format

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: write

env:
  ACT: false

jobs:
  format:
    name: Format Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Format Repository
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
