name: Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Setup Cache
        uses: DeterminateSystems/flakehub-cache-action@v1

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Format Repo
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
