name: Format

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Formatter
        run: nix-build .github/format.nix

      - name: Format Repo
        run: result/bin/treefmt

      - name: Check for Changes
        run: git diff --exit-code
