name: Format

on:
  push:
    branches: [main]
  pull_request:

env:
  ACT: false

jobs:
  format:
    name: Format Repository
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
      - extras=s3-cache

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Format Repository
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
