name: Check Inputs

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Flake Inputs
        uses: DeterminateSystems/flake-checker-action@v9
