name: Check Inputs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  follow:
    runs-on: ubuntu-latest

    steps:
      - run: groups
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            accept-flake-config = true
            build-users-group =

      - name: Setup Cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Follow Flake Inputs
        run: nix run github:fzakaria/nix-auto-follow -- -i

      - name: Lock Flake Inputs
        run: nix flake lock

      - name: Check for Changes
        run: git diff --exit-code

  check:
    runs-on: ubuntu-latest

    needs: follow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Flake Inputs
        uses: DeterminateSystems/flake-checker-action@v9
