name: Prebuild

on:
  push:
    branches: [main]
  pull_request:

env:
  ACT: false

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run Prebuild Scripts
        run: find systems/*/*/ -name prebuild.sh -exec bash {} \;

      - name: Format Code
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
