name: Prebuild

on:
  push:
    branches: [main]
  pull_request:

env:
  ACT: false

jobs:
  compose:
    name: Compose to Nix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Convert Docker Compose Files
        run: find . -name compose.sh -exec {} \;

      - name: Format Code
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
