name: Prebuild

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            accept-flake-config = true
            build-users-group =

      - name: Setup Cache
        uses: nix-community/cache-nix-action@v6
        if: ${{ !env.ACT }}
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Prebuild Scripts
        run: find systems/*/*/ -name prebuild.sh -exec bash {} \;

      - name: Format Code
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
