name: Prebuild

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Prebuild Scripts
        run: find systems/*/*/ -name prebuild.sh -exec bash {} \;

      - name: Format Code
        run: nix fmt

      - name: Check for Changes
        run: git diff --exit-code
