name: Retry

on:
  workflow_dispatch:
    inputs:
      id:
        required: true
jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Rerun ${{ inputs.id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run watch ${{ inputs.id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.id }} --failed
