name: Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # runs weekly on Saturday at 00:00

env:
  ACT: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          token: ${{ secrets.WORKFLOWS_TOKEN }}
          commit-msg: "chore(deps): update flake.lock"
          git-author-email: "github-actions[bot]@users.noreply.github.com"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"
          nix-options: "--accept-flake-config"
