name: Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # runs weekly on Saturday at 00:00

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            accept-flake-config = true
            build-users-group =

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          token: ${{ secrets.WORKFLOWS_TOKEN }}
          commit-msg: "chore(deps): update flake.lock"
          git-author-email: "github-actions[bot]@users.noreply.github.com"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"
          nix-options: "--accept-flake-config"
